### ISSUE TITLE
Bump a gem version

### ISSUE THREAD

**Issue by 304** [Fivell/activeresource-response#20]
I have noticed that rubygems has a old version of this gem (1.1.1) (https://rubygems.org/gems/activeresource-response) which does not contain commits related to Rails 5 support.

Would it be possible to release a new version of the gem based on current master?

Thanks in advance!

**Comment by 304** [comment]
Hi @Fivell,

I've noticed an opened PR related to the version bump (https://github.com/Fivell/activeresource-response/pull/22), however it's not merged yet. 

Have you faced any problems during an update? Can I somehow assist you with it?

**Comment by Fivell** [comment]
@luk4s @304 
Pushing gem to https://rubygems.org...
Successfully registered gem: activeresource-response (1.2.0)
